### ISSUE TITLE
Can not run (see) app at monitor

### ISSUE THREAD

**Issue by dronecz** [CCHS-Melbourne/openpnp-kiosk#2]
After I deployed image from balena Cloud to my RPi 4, I can see just balena logo at my monitor and I supposed to see OpenPnP app (Í guess). 

Can you please navigate me what I should check/setup/run in balena cloud console? 

Thanks for help.

**Comment by brainstorm** [comment]
Hey, thanks for trying! Can you copy and paste the output from the Balena console on the web?

**Comment by dronecz** [comment]
Sure, here: 

27.05.20 17:42:04 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:42:05 (+0200) Service exited 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:42:31 (+0200) Restarting service 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:42:04 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  Starting X in 2 seconds
27.05.20 17:42:04 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:42:04 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:42:04 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:42:04 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:42:32 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  Starting X in 2 seconds
27.05.20 17:42:32 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:42:32 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:42:32 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:42:32 (+0200) Service exited 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:43:24 (+0200) Restarting service 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:42:32 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  Starting X in 2 seconds
27.05.20 17:42:32 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:42:32 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:42:32 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:42:32 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:43:25 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  Starting X in 2 seconds
27.05.20 17:43:25 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:43:25 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:43:25 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:43:25 (+0200) Service exited 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:44:26 (+0200) Restarting service 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:43:25 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  Starting X in 2 seconds
27.05.20 17:43:25 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:43:25 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:43:25 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:43:25 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:44:26 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  Starting X in 2 seconds
27.05.20 17:44:26 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:44:26 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:44:26 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:44:27 (+0200) Service exited 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:45:28 (+0200) Restarting service 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'
27.05.20 17:44:26 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  Starting X in 2 seconds
27.05.20 17:44:26 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:44:26 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:44:26 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:44:26 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:45:28 (+0200)  main  start.sh: line 2: $'\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 3: $'true\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 4: $'\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 7: $'\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 16: $'\r': command not found
27.05.20 17:45:28 (+0200)  main  Starting X in 2 seconds
27.05.20 17:45:28 (+0200)  main  sleep: invalid time interval ‘2\r’
27.05.20 17:45:28 (+0200)  main  Try 'sleep --help' for more information.
27.05.20 17:45:28 (+0200)  main  start.sh: line 20: $'startx\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 21: $'\r': command not found
27.05.20 17:45:28 (+0200)  main  start.sh: line 27: syntax error: unexpected end of file
27.05.20 17:45:29 (+0200) Service exited 'main sha256:9eb8cebe41c6a90f02af46580744d727125973ada917951a10203f7f3e382ff0'

**Comment by brainstorm** [comment]
Looks like windows might have messed up with the newlines of `start.sh`? Could you try using WSL to clone the repo and operate `balena push <APP>`?:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by dronecz** [comment]
I had to use this command: 
`balena.exe push <app> --convert-eol --dockerfile \Dockerfile.raspberrypi3-64` in WSL, but it did deploy OK. I can open OpenPnP and setup USB cam, but I can not see RPi camera module. I guess this has to be enabled somehow. 

One think which is not user friendly is that, you can not shutdown or restart it from OS. You have to use Balena dashboard to do it. Maybe there is some settings in dashboard which can change that. 

As I can now work in app, I think this issue is resolved,

**Comment by brainstorm** [comment]
Good news, glad you persisted and finally succeeded! :)

Good point with the shutdown/restart sequence, I'll give it some thought.
