### ISSUE TITLE
Java for armhf

### ISSUE THREAD

**Issue by dronecz** [CCHS-Melbourne/openpnp-kiosk#3]
I´m trying to install OpenPnP on Raspbian by following commands in [dockerfile for RPi](https://github.com/CCHS-Melbourne/openpnp-kiosk/blob/master/Dockerfile.raspberrypi3-64), but I stoped at point where I should install Java from Correto (`# Install Corretto, since OpenJDK seems to be only available as JRE in Debian bullseye for ARM64`) . I can download package, but when I try to install it, OS gives me error that this package is not for armhf architecture. 

Do you know please, if there is this file for Raspbian? I tried to search it with Google, but so far no luck. 

Thanks.

**Comment by brainstorm** [comment]
That's right, `openpnp-kiosk` is aimed at Raspberry Pi OSs of 64-bits, armhf (ARM hard float) is usually meant for 32-bit... if you want to go with raspbian, you should get this one:

https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370
