### ISSUE TITLE
Balena.io guide updated

### ISSUE THREAD

**Issue by Moriquendi001** [CCHS-Melbourne/openpnp-kiosk#5]
The linked guide on Balena.io has been updated (May 28th) to use the "Deploy with Balena" method in place of the CLI method referred to in the readme, does anyone have a link to the old guide?

Edit: Succeed eventually by following process [here](https://github.com/CCHS-Melbourne/openpnp-kiosk/issues/1#issue-619726922)

**Comment by brainstorm** [comment]
Glad that helped! ;)
