### ISSUE TITLE
Configuration load error(NVIDIA Jetson Nano)

### ISSUE THREAD

**Issue by snow19911226** [CCHS-Melbourne/openpnp-kiosk#6]
I followed instruction of #1 (in the step 6 I change the Dockerfile.raspberrypi3-64 to Dockerfile.jetson-nano) and got errors.
![configuration_load_err](https://user-images.githubusercontent.com/26074576/106160082-6a4d5480-61c0-11eb-8677-01b496b926e6.jpeg)

**Comment by brainstorm** [comment]
I'll resume/polish this work once https://github.com/openpnp/opencv/pull/56 and https://github.com/openpnp/opencv/pull/59 are properly solved... once we have the release engineering under control, I'll fix those corner cases and it'll be easier to use, promise! ;)

**Comment by G-Pereira** [comment]
I am also running into this on a Jetson Nano.

**Comment by brainstorm** [comment]
Solved.
